<a href="https://colab.research.google.com/github/imyoungchae/Python_study/blob/main/matrix2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

mat1=[[1,2,3,4],
      [5,6,7,8]]

mat2=[[9,10,11,12],
      [13,14,15,16]]

mat3=[[17,18,19,20],
      [21,22,23,24]]

tensor1=tf.constant([mat1,mat2,mat3])

print("rank: ",tf.rank(tensor1))

print("tensorl: ",tensor1)

rank:  tf.Tensor(3, shape=(), dtype=int32)
tensorl:  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [3]:
# 스택 함수를 이용하여 결합하기

tensor2=tf.stack([mat1,mat2,mat3])
print("rank: ",tf.rank(tensor2))

print("tensorl: ",tensor2)


rank:  tf.Tensor(3, shape=(), dtype=int32)
tensorl:  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)
