<a href="https://colab.research.google.com/github/imyoungchae/Python_study/blob/main/matrix1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf

# 2차원 배열 정의
list_of_list=[[10,20],[30,40]]

# 텐서 변환(constant 함수에 2차원 배열 입력)
mat1=tf.constant(list_of_list)

# 랭크 확인
print("rank:",tf.rank(mat1))

# 텐서 출력
print("matl:",mat1)

rank: tf.Tensor(2, shape=(), dtype=int32)
matl: tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [7]:
# 2차원 행렬에 스칼라 값 곱하기
element_bc=tf.math.multiply(mat1,3)
print("*3 result:",element_bc)
print("*3 rank:",tf.rank(element_bc))
print()

element_bc1=tf.math.multiply(mat1,5)
print("*5 result:",element_bc1)
print("*5 rank:",tf.rank(element_bc1))

*3 result: tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
*3 rank: tf.Tensor(2, shape=(), dtype=int32)

*5 result: tf.Tensor(
[[ 50 100]
 [150 200]], shape=(2, 2), dtype=int32)
*5 rank: tf.Tensor(2, shape=(), dtype=int32)


In [9]:
# 행렬 곱 연산
matrix_1=[[1,2],[3,4]]
matrix_2=[[10,20],[30,40]]
matr1=tf.constant(matrix_1)
matr2=tf.constant(matrix_2)

print("matr1: ",matr1)
print()
print("matr2: ",matr2)
print()

mat_mul=tf.matmul(matr1,matr2)
print("result:",mat_mul)
print("result rank:",tf.rank(mat_mul))

matr1:  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

matr2:  tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)

result: tf.Tensor(
[[ 70 100]
 [150 220]], shape=(2, 2), dtype=int32)
result rank: tf.Tensor(2, shape=(), dtype=int32)


In [10]:
# 행렬 덧셈 계산
add_matr=tf.math.add(matr1,matr2)
print("result:",add_matr)
print("result rank:",tf.rank(add_matr))

result: tf.Tensor(
[[11 22]
 [33 44]], shape=(2, 2), dtype=int32)
result rank: tf.Tensor(2, shape=(), dtype=int32)
